### ISSUE TITLE
Create Slash Command to list log

### ISSUE THREAD

**Issue by raae** [queen-raae/yoga-pirates-bot#6]
https://discordjs.guide/slash-commands/response-methods.html

`/yoga` should give the number of yoga days, and maybe days per month?

Should is also be possible to get all sessions of a week, with the notes?

What do you think @davidwessman?

**Comment by davidwessman** [comment]
Sounds cool 😊 maybe we can add scopes? Like 

/yoga week
/yoga year
/yoga streak

Not sure how other bots works but it seems like you would want this in DM to avoid spamming other people?

**Comment by raae** [comment]
I like these commands!

I think slash commands can be made to give private responses...
